config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index]
  resources :invitations, only: [:create, :destroy, :update] do
    collection do  
      get "friends"
      get "suggested"
      get "pending"
    end
  end
  
  root "posts#index"
  
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id" 
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validate :must_contain_image_or_body
  validate :acceptable_image

  private

  def must_contain_image_or_body
    if image.attached? == false && body.nil?
      errors.add(:base, "Image or body must be present")
    end
  end

  def acceptable_image
    return unless image.attached?

    unless image.blob.byte_size <= 1.megabyte
      errors.add(:image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPEG or PNG")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :create]

  def index
    @post = Post.new
    @posts = Post.includes(:likes, :author, comments: [:likes, :post, :author]).order(created_at: :desc, "comments.created_at": :desc).with_attached_image.all
  end

  def show
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      flash[:alert] = @post.errors.full_messages.join(" ")
      redirect_to root_path
    end
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save 
        format.turbo_stream
      else
        flash[:alert] = @post.errors.full_messages.join(" ")
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/people_region/_friend.html.erb
<div id="invitation_<%= invitation.id %>" class="h-20 flex items-center p-2">
    <%= link_to friend, data: { turbo_frame: "_top" }, class: "h-full flex items-center gap-2 p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" do %>
        <%= image_tag friend.profile_photo, alt: "Profile photo", class: "w-12 h-12 rounded-full" %>
        <p class="font-medium"><%= "#{friend.first_name} #{friend.last_name}" %></p>
    <% end %>

    <%= link_to "Unfriend", invitation, data: { "turbo-method": :delete }, class: "h-full flex items-center ml-auto p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" %>
</div>

app/views/posts/people_region/_pending_invitation.html.erb
<div id="invitation_<%= invitation.id %>" class="h-20 flex items-center p-2">
    <%= link_to invitation.user, data: { turbo_frame: "_top" }, class: "h-full flex items-center gap-2 p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" do %>
        <%= image_tag invitation.user.profile_photo, alt: "Profile photo", class: "w-12 h-12 rounded-full" %>
        <p class="font-medium"><%= "#{invitation.user.first_name} #{invitation.user.last_name}" %></p>
    <% end %>

    <%= form_with url: invitation_path(invitation), method: :patch, class: "h-full flex items-center ml-auto" do |form| %>
        <%= form.hidden_field :inviting_user_id, value: invitation.user.id %>
        <%= form.submit "Accept", class: "h-full p-2 hover:bg-red-200 focus:bg-red-100 rounded-md hover:cursor-pointer" %>
    <% end %>

    <%= form_with model: invitation, method: :delete, class: "h-full flex items-center" do |form| %>
        <%= form.submit "Reject", class: "h-full p-2 hover:bg-red-200 focus:bg-red-100 rounded-md hover:cursor-pointer" %>
    <% end %>
</div>

app/views/posts/people_region/_people_region.html.erb
<div id="people-navbar" data-controller="people-navbar" class="fixed p-2 right-0 bottom-0 top-[5vh] mt-2 w-[400px] mx-2 rounded-md bg-red-50 drop-shadow-md overflow-y-scroll">
    <div class="flex p-2 h-[100px] items-center justify-around border-b border-slate-200">
        <%= link_to "All friends", friends_invitations_path, data: { turbo_frame: "people-options" }, class: "flex items-center px-2 py-1 rounded-md h-3/5 text-base hover:cursor-pointer hover:bg-red-200 active:bg-red-100" %>
        <%= link_to "Suggestions", suggested_invitations_path, data: { turbo_frame: "people-options" }, class: "flex items-center px-2 py-1 rounded-md h-3/5 text-base hover:cursor-pointer hover:bg-red-200 active:bg-red-100" %>
        <%= link_to pending_invitations_path, data: { turbo_frame: "people-options" }, class: "flex flex-col justify-center px-2 py-1 rounded-md h-3/5 text-base hover:cursor-pointer hover:bg-red-200 active:bg-red-100" do %>
            <p>Friend Requests</p>
            <%= render "shared/pending_counter" %>
        <% end %>
    </div>

    <%= turbo_frame_tag "people-options", src: suggested_invitations_path do %>
    <% end %>
</div>

app/views/posts/people_region/_suggested_friend.html.erb
<div class="h-20 flex items-center p-2">
    <%= link_to suggested_friend, data: { turbo_frame: "_top" }, class: "h-full flex items-center gap-2 p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" do %>
        <%= image_tag suggested_friend.profile_photo, alt: "Profile photo", class: "w-12 h-12 rounded-full" %>
        <p class="font-medium"><%= "#{suggested_friend.first_name} #{suggested_friend.last_name}" %></p>
    <% end %>

    <div id="suggested_friend_<%= suggested_friend.id %>" class="h-full flex items-center ml-auto">
        <% unless invitation %>
            <%= render "shared/add_friend_button", friend: suggested_friend %>
        <% else %>
            <%= render "shared/cancel_friend_request", friend: suggested_friend, invitation: invitation %>
        <% end %>
    </div>
</div>