config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index]
  resources :invitations, only: [:create, :destroy, :update] do
    collection do  
      get "friends"
      get "suggested"
      get "pending"
    end
  end
  
  root "posts#index"
  
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: "User", foreign_key: "user_id"
  has_many :likes, as: :likeable, dependent: :destroy

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = current_user.comments.build(comment_params)

        respond_to do |format|
            if @comment.save
                format.turbo_stream
            else
                flash[:alert] = @post.errors.full_messages.join(" ")
                format.html { redirect_to root_path }
            end
        end
    end

    def destroy
        @comment = current_user.comments.find(params[:id])
        @comment.destroy

        respond_to do |format|
            format.turbo_stream
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="py-2">
    <div class="flex items-center gap-2 drop-shadow-md">
        <%= link_to comment.author, data: { turbo_frame: "_top" } do %>
            <%= image_tag comment.author.profile_photo, alt: "Profile photo", class: "w-6 h-6 rounded-full" %>
        <% end %>

        <%= link_to comment.author, data: { turbo_frame: "_top" } do %>
            <p class="text-sm font-semibold"><%= "#{comment.author.first_name} #{comment.author.last_name}" %></p>
        <% end %>

        <p class="text-sm text-slate-500"><%= "#{time_ago_in_words(comment.created_at)} ago" %></p>
    </div>

    <div>
        <p class="text-base"><%= comment.body %></p>
    </div>

    <%= render "likes/like_counter", likeable: comment %>

    <div class="flex flex-row">
        <%= render "likes/like_region", likeable: comment %>
        
        <% if comment.author == current_user %>
            <div class="ml-auto">
                <%= button_to comment_path(comment), method: :delete, class: "text-sm flex items-center self-center px-2 py-0.5 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
                    Remove
                    <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>trash-can-outline</title><path d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M7,6H17V19H7V6M9,8V17H11V8H9M13,8V17H15V8H13Z" /></svg>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_with model: Comment.new, data: { controller: "form", action: "turbo:submit-end->form#clear" }, class: "flex" do |form| %>
    <%= form.text_area :body, rows: 2, placeholder: "Write a comment", data: { "form-target": "textArea" }, class: "w-full resize-none rounded-md bg-red-50 focus:ring-0 border-0 p-3" %>
    <%= form.hidden_field :post_id, value: post.id %>
    <%= button_tag data: { action: "form#preventEmpty" }, class: "self-center p-3 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>send-variant-outline</title><path d="M3 20V4L22 12M5 17L16.85 12L5 7V10.5L11 12L5 13.5M5 17V7 13.5Z" /></svg>
    <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments_#{@comment.post_id}", @comment %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>