config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index]
  resources :invitations, only: [:create, :destroy, :update] do
    collection do  
      get "friends"
      get "suggested"
      get "pending"
    end
  end
  
  root "posts#index"
  
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
require 'digest/md5'

class User < ApplicationRecord
  before_save :capitalize_name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[github google_oauth2]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :invitations, dependent: :destroy
  # Shows this user's pending invitations (sent by others)
  has_many :pending_invitations, -> { where(confirmed: false) }, class_name: "Invitation", foreign_key: "friend_id", dependent: :destroy
  has_many :accepted_invitations, -> { where(confirmed: true) }, class_name: "Invitation", foreign_key: "friend_id", dependent: :destroy
  has_many :likes, class_name: "Like", foreign_key: "user_id", dependent: :destroy
  has_many :liked_posts, -> { where(likeable_type: "Post") }, class_name: "Like", foreign_key: "user_id",  dependent: :destroy
  has_many :liked_comments, -> { where(likeable_type: "Comment") }, class_name: "Like", foreign_key: "user_id",  dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_one_attached :background_photo, dependent: :destroy

  validate :validate_attachments

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      if auth.provider == "google_oauth2"
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
      else
        user.first_name = auth.info.name
        user.last_name = nil
      end

      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.image = auth.info.image 
    end
  end

  def friends
    user_friends = Invitation.where(user_id: self.id).where(confirmed: true).pluck(:friend_id)
    user_friend_of = Invitation.where(friend_id: self.id).where(confirmed: true).pluck(:user_id)
    User.where(id: [user_friends + user_friend_of])
  end

  def suggested_friends
    User.where.not(id: friends).where.not(id: id).where.not(id: pending_invitations.pluck(:user_id))
  end
  
  def profile_photo
    return avatar if avatar.attached?
    return image if image
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "https://www.gravatar.com/avatar/#{hash}" 
  end

  private

  def capitalize_name
    first_name&.capitalize!
    last_name&.capitalize!
  end

  def email_required?
    provider.blank?
  end

  def validate_attachments
    validate_attachment(avatar)
    validate_attachment(background_photo)
  end

  def validate_attachment(attachment)
    return unless attachment.attached?

    unless attachment.blob.byte_size <= 1.megabyte
      errors.add(:attachment.name.capitalize, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(attachment.content_type)
      errors.add(:"#{attachment.name.capitalize}", "must be a JPEG or PNG")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: [:github, :google_oauth2]

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url, alert: "Couldn't authenticate with GitHub: #{@user.errors.full_messages.join("\n")}"
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: "Couldn't authenticate with Google: #{@user.errors.full_messages.join("\n")}"
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
    if @user.persisted? 
      UserMailer.with(user: @user).welcome_email.deliver_later
    end
  end
  
  # After user update's his profile, redirect to that profile
  def user_root_path
    current_user
  end

  protected

  def update_resource(resource, params)
    resource.provider.blank? ? super : resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    flash[:alert] = ""
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.includes(posts: [:likes, {comments: [:likes, :author, :post]}]) 
                    .order("posts.created_at DESC", "comments.created_at DESC")
                    .find(params[:id])
        @invitation = Invitation.find_invitation(current_user, @user).take
    end    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend.html.erb
<div class="h-20 flex items-center p-2">
    <%= link_to friend, class: "h-full w-full flex items-center gap-2 p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" do %>
        <%= image_tag friend.profile_photo, alt: "Profile photo", class: "w-12 h-12 rounded-full" %>
        <p class="font-medium"><%= "#{friend.first_name} #{friend.last_name}" %></p>
    <% end %>
</div>

app/views/users/_user_options.html.erb
<% if current_user == @user %>
    <%# Literally do nothing %>
<% elsif current_user.friends.include?(@user) %>
    <%= link_to "Unfriend", invitation_path(@invitation, user_profile: @user.id), data: { turbo_method: :delete }, class: "p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" %>
<% elsif current_user.pending_invitations.pluck(:user_id).include?(@user.id) %>
    <p class="font-bold text-red-500">Pending request</p>
    <%= form_with url: invitation_path(@invitation, user_profile: @user.id), method: :patch do |form| %>
        <%= form.hidden_field :inviting_user_id, value: @invitation.user.id %>
        <%= form.submit "Accept", class: "p-2 hover:bg-red-200 focus:bg-red-100 rounded-md hover:cursor-pointer" %>
    <% end %>

    <%= form_with url: invitation_path(@invitation, user_profile: @user.id), method: :delete do |form| %>
        <%= form.submit "Reject", class: "p-2 hover:bg-red-200 focus:bg-red-100 rounded-md hover:cursor-pointer" %>
    <% end %>
<% elsif @user.pending_invitations.pluck(:user_id).include?(current_user.id) %>
    <%= link_to "Cancel request", invitation_path(@invitation, user_profile: @user.id), data: { turbo_method: :delete }, class: "p-2 hover:bg-red-200 focus:bg-red-100 rounded-md" %>
<% else %>
    <%= form_with url: invitations_path(user_profile: @user.id), method: :post do |form| %>
        <%= form.hidden_field :friend_id, value: @user.id %>
        <%= form.submit "Add a friend", class: "p-2 hover:bg-red-200 focus:bg-red-100 rounded-md hover:cursor-pointer" %>
    <% end %>
<% end %>

<% if @user == current_user %>
    <%= link_to edit_user_registration_path, class: "flex items-center p-3 rounded-full hover:bg-red-100 active:bg-red-200" do %>
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Edit profile pencil</title><path d="M14.06,9L15,9.94L5.92,19H5V18.08L14.06,9M17.66,3C17.41,3 17.15,3.1 16.96,3.29L15.13,5.12L18.88,8.87L20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18.17,3.09 17.92,3 17.66,3M14.06,6.19L3,17.25V21H6.75L17.81,9.94L14.06,6.19Z" /></svg>
        Edit profile
    <% end %>
<% end %>

app/views/users/show.html.erb
<div class="w-full h-[50vh] bg-red-50 drop-shadow-md rounded-md">
    <div class="w-[900px] h-full mx-auto">
        <div class="w-full h-3/5 bg-gradient-to-b from-red-200 to-red-400 rounded-md">
            <% if @user.background_photo.attached? %>
                <%= image_tag @user.background_photo, alt: "Background photo", class:"w-full h-full rounded-md" %>
            <% end %>
        </div>

        <div class="flex px-6">
            <%= image_tag @user.profile_photo, alt: "Profile photo", class:"w-36 h-36 relative -top-8 rounded-full border-4 border-red-50" %>
            
            <div class="pl-2 pt-6">
                <p class="font-semibold text-xl"><%= "#{@user.first_name} #{@user.last_name}" %></p>
            </div>

            <div class="flex items-center gap-2 ml-auto self-end">
                <%= render "user_options" %>
            </div>
        </div>
    </div>
</div>

<div class="grid grid-cols-[300px_1fr_600px_1fr] w-full">
    <div>
        <div class="sticky top-[calc(5vh_+_0.5rem)] h-screen p-2 rounded-md bg-red-50 drop-shadow-md overflow-y-scroll">
            <p class="px-4 text-2xl font-semibold">Friends</p>
            <%= render partial: "friend", collection: @user.friends %>
        </div>
    </div>

    <div class="col-start-3">
        <div id="posts" class="flex flex-col gap-2">
            <%= render @user.posts %>
        </div>
    </div>
</div>