config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index]
  resources :invitations, only: [:create, :destroy, :update] do
    collection do  
      get "friends"
      get "suggested"
      get "pending"
    end
  end
  
  root "posts#index"
  
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id" 
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validate :must_contain_image_or_body
  validate :acceptable_image

  private

  def must_contain_image_or_body
    if image.attached? == false && body.nil?
      errors.add(:base, "Image or body must be present")
    end
  end

  def acceptable_image
    return unless image.attached?

    unless image.blob.byte_size <= 1.megabyte
      errors.add(:image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPEG or PNG")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :create]

  def index
    @post = Post.new
    @posts = Post.includes(:likes, :author, comments: [:likes, :post, :author]).order(created_at: :desc, "comments.created_at": :desc).with_attached_image.all
  end

  def show
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      flash[:alert] = @post.errors.full_messages.join(" ")
      redirect_to root_path
    end
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save 
        format.turbo_stream
      else
        flash[:alert] = @post.errors.full_messages.join(" ")
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, data: { controller: "form", action: "turbo:submit-end->form#clear" } do |form| %>
    <div class="bg-red-50 rounded-md">
        <%= form.text_area :body, rows: "4", placeholder: "What's on your mind, #{current_user.first_name}?", data: { "form-target": "textArea" }, class: "w-full resize-none rounded-md bg-red-50 focus:ring-0 border-0 p-3" %>
        
        <div class="p-3">
            <%= form.label :image, "Upload image", class: "block mb-2 text-sm font-medium text-black" %>
            <%= form.file_field :image, data: { form_target: "fileField" }, class: "p-1 block w-full text-sm text-gray-900 border-0 rounded-lg cursor-pointer text-gray-400 focus:outline-none bg-red-100 placeholder-gray-400" %>
            <p class="mt-1 text-sm text-slate-800">PNG, JPG (MAX. 1MB).</p>
        </div>

        <hr>
        <%= form.submit "Post", data: { action: "form#preventEmpty" },  class: "bg-red-50 w-full mt-2 rounded-md p-2 hover:cursor-pointer hover:bg-red-100 focus:bg-red-200" %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>" class="flex flex-col gap-2 w-full p-2 bg-red-50 rounded-md">
    <%= turbo_frame_tag "editable_section_post_#{post.id}" do %>
        <%= turbo_stream.update "flash" do %>
            <%= render "shared/flash" %>
        <% end %>

        <%= render "posts/post_header", post: post %>
        
        <% unless post.body.nil? %>
            <div class="py-2">
                <%= post.body %>
            </div>
        <% end %>

        <% if post.image.attached? %>
            <div class="py-2">
                <%= image_tag post.image, class: "rounded-sm" %>
            </div>
        <% end %>

        <%= render "likes/like_counter", likeable: post %>

        <div class="flex border-t border-b border-slate-200 py-2 gap-2 text-base">
            <%= render "likes/like_region", likeable: post %>

            <% if post.author == current_user %>
                <div class="flex gap-2 ml-auto">
                    <%= link_to edit_post_path(post), class: "flex items-center self-center px-3 py-1 gap-2 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
                        Edit
                        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>file-edit-outline</title><path d="M10 20H6V4H13V9H18V12.1L20 10.1V8L14 2H6C4.9 2 4 2.9 4 4V20C4 21.1 4.9 22 6 22H10V20M20.2 13C20.3 13 20.5 13.1 20.6 13.2L21.9 14.5C22.1 14.7 22.1 15.1 21.9 15.3L20.9 16.3L18.8 14.2L19.8 13.2C19.9 13.1 20 13 20.2 13M20.2 16.9L14.1 23H12V20.9L18.1 14.8L20.2 16.9Z" /></svg>
                    <% end %>

                    <%= button_to post_path(post), method: :delete, class: "flex items-center self-center px-3 py-1 gap-2 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
                        Remove
                        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>trash-can-outline</title><path d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M7,6H17V19H7V6M9,8V17H11V8H9M13,8V17H15V8H13Z" /></svg>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>

    <div>
        <%= render "comments/comment_form", post: post %>
    </div>

    <%# Post ID is needed to target correct Post with comment via turbo streams %>
    <div id="comments_<%= post.id %>" class="divide-y border-t border-slate-400 pt-2">
        <%= render post.comments %>
    </div>
</div>

app/views/posts/_post_header.html.erb
<div class="flex gap-2 items-center drop-shadow-md">
    <%= link_to post.author, data: { turbo_frame: "_top" } do %>
        <%= image_tag post.author.profile_photo, alt: "Profile photo", class: "w-16 h-16 rounded-full" %>
    <% end %>
    <div>
        <%= link_to post.author, data: { turbo_frame: "_top" } do %>
            <p class="text-base font-semibold"><%= "#{post.author.first_name} #{post.author.last_name}" %></p>
        <% end %>
        <p class="text-sm text-slate-500"><%= "#{time_ago_in_words(post.created_at)} ago" %></p>
    </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", @post %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove "post_#{@post.id}" %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "editable_section_post_#{@post.id}" do %>
    <%= render "post_header", post: @post %>
    
    <div>
        <%= form_with model: @post, html: { id: "edit-post" } do |form| %>
            <div class="bg-red-50 rounded-md">
                <%= form.text_area :body, class: "w-full resize-none rounded-md bg-red-50 focus:ring-0 p-3 border-0" %>
            </div>

            <div class="p-3">
                <%= form.label :image, "Upload image", class: "block mb-2 text-sm font-medium text-black" %>
                <%= form.file_field :image, class: "p-1 block w-full text-sm text-gray-900 border-0 rounded-lg cursor-pointer text-gray-400 focus:outline-none bg-red-100 placeholder-gray-400" %>
                <p class="mt-1 text-sm text-slate-800">PNG, JPG (MAX. 1MB).</p>
            </div>
        <% end %>
    </div>

    <%= render "likes/like_counter", likeable: @post %>

    <div class="flex border-t border-b border-slate-200 py-2 gap-2 text-base">
        <% if @post.author == current_user %>
            <%= button_tag form: "edit-post", class: "flex items-center self-center px-3 py-1 gap-2 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
                Save
                <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>content-save-check-outline</title><path d="M14 12.8C13.5 12.31 12.78 12 12 12C10.34 12 9 13.34 9 15C9 16.31 9.84 17.41 11 17.82C11.07 15.67 12.27 13.8 14 12.8M11.09 19H5V5H16.17L19 7.83V12.35C19.75 12.61 20.42 13 21 13.54V7L17 3H5C3.89 3 3 3.9 3 5V19C3 20.1 3.89 21 5 21H11.81C11.46 20.39 11.21 19.72 11.09 19M6 10H15V6H6V10M15.75 21L13 18L14.16 16.84L15.75 18.43L19.34 14.84L20.5 16.25L15.75 21" /></svg>
            <% end %>

            <%= link_to @post, class: "flex items-center self-center px-3 py-1 gap-2 rounded-full hover:bg-red-100 focus:bg-red-200" do %>
                Cancel
                <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>close-outline</title><path d="M3,16.74L7.76,12L3,7.26L7.26,3L12,7.76L16.74,3L21,7.26L16.24,12L21,16.74L16.74,21L12,16.24L7.26,21L3,16.74M12,13.41L16.74,18.16L18.16,16.74L13.41,12L18.16,7.26L16.74,5.84L12,10.59L7.26,5.84L5.84,7.26L10.59,12L5.84,16.74L7.26,18.16L12,13.41Z" /></svg>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/posts/index.html.erb
<div class="col-start-2">
    <%= render "form" %>
    <div id="posts" class="flex flex-col gap-2 mt-2">
        <%= render @posts %>
    </div>
</div>

<%= render "posts/people_region/people_region" %>

app/views/posts/show.html.erb
<%= render "post", post: @post %>